-- ============================================================================
-- NullMarket — Phase 16: BigQuery Warehouse Build
-- ============================================================================
-- PURPOSE
--   Recreate the final BigQuery warehouse from the Spark-curated Parquet layer
--   stored in Google Cloud Storage.
--
-- ASSUMPTIONS
--   - Project: nullmarket-retail-de
--   - Dataset: nullmarket_warehouse
--   - Region: northamerica-northeast2
--   - Curated source: gs://nullmarket-retail-de-data/curated
--   - The BigQuery dataset already exists in the Toronto region.
--
-- BUSINESS RULES
--   - No order_status filter is applied because the authoritative NullMarket
--     requirements define no revenue inclusion/exclusion rule by order status.
--   - No SCD Type 2 behavior is implemented or implied.
--
-- PHYSICAL DESIGN
--   - fact_sales is partitioned by order_date and clustered by
--     product_key, store_key.
--   - fact_inventory_snapshot is partitioned by snapshot_date and clustered by
--     store_key, product_key.
--
-- IMPORTANT
--   The two Spark-curated fact Parquet datasets do not physically contain the
--   BigQuery partition DATE columns. This script therefore loads each fact into
--   a temporary staging table, derives the business date through dim_date, then
--   creates the final partitioned and clustered fact table.
-- ============================================================================


-- ============================================================================
-- 1. DIMENSION TABLES
-- ============================================================================

-- ---------------------------------------------------------------------------
-- dim_date
-- Grain: one row per calendar date.
-- date_key is the deterministic YYYYMMDD warehouse key generated by Spark.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS
`nullmarket-retail-de.nullmarket_warehouse.dim_date`
(
    date_key        INT64,
    full_date       DATE,
    day_of_week     INT64,
    day_name        STRING,
    day_of_month    INT64,
    week_of_year    INT64,
    month_number    INT64,
    month_name      STRING,
    quarter_number  INT64,
    year            INT64
);

LOAD DATA OVERWRITE
`nullmarket-retail-de.nullmarket_warehouse.dim_date`
FROM FILES (
    format = 'PARQUET',
    uris = [
        'gs://nullmarket-retail-de-data/curated/dim_date/part-*.parquet'
    ]
);


-- ---------------------------------------------------------------------------
-- dim_product
-- Grain: one row per current product.
-- product_key is the warehouse surrogate key.
-- product_id remains the source-system business key.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS
`nullmarket-retail-de.nullmarket_warehouse.dim_product`
(
    product_key   INT64,
    product_id    STRING,
    product_name  STRING,
    category      STRING,
    subcategory   STRING,
    brand         STRING,
    list_price    NUMERIC,
    active_flag   BOOL
);

LOAD DATA OVERWRITE
`nullmarket-retail-de.nullmarket_warehouse.dim_product`
FROM FILES (
    format = 'PARQUET',
    uris = [
        'gs://nullmarket-retail-de-data/curated/dim_product/part-*.parquet'
    ]
);


-- ---------------------------------------------------------------------------
-- dim_store
-- Grain: one row per current store.
-- store_key is the warehouse surrogate key.
-- store_id remains the source-system business key.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS
`nullmarket-retail-de.nullmarket_warehouse.dim_store`
(
    store_key   INT64,
    store_id    STRING,
    store_name  STRING,
    city        STRING,
    province    STRING,
    region      STRING,
    store_type  STRING,
    open_date   DATE
);

LOAD DATA OVERWRITE
`nullmarket-retail-de.nullmarket_warehouse.dim_store`
FROM FILES (
    format = 'PARQUET',
    uris = [
        'gs://nullmarket-retail-de-data/curated/dim_store/part-*.parquet'
    ]
);


-- ============================================================================
-- 2. FACT_SALES
-- ============================================================================

-- ---------------------------------------------------------------------------
-- Temporary staging table
--
-- This schema matches the Spark-curated Parquet exactly.
-- order_date is intentionally absent here because Spark stores date_key only.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE TABLE
`nullmarket-retail-de.nullmarket_warehouse._stg_fact_sales`
(
    date_key         INT64,
    store_key        INT64,
    product_key      INT64,
    order_id         STRING,
    line_number      INT64,
    quantity         INT64,
    unit_price       NUMERIC,
    discount_amount  NUMERIC,
    unit_cost        NUMERIC,
    gross_sales      NUMERIC,
    net_sales        NUMERIC,
    gross_margin     NUMERIC
);

LOAD DATA OVERWRITE
`nullmarket-retail-de.nullmarket_warehouse._stg_fact_sales`
FROM FILES (
    format = 'PARQUET',
    uris = [
        'gs://nullmarket-retail-de-data/curated/fact_sales/part-*.parquet'
    ]
);

-- ---------------------------------------------------------------------------
-- Final sales fact
--
-- Grain:
--   one row per validated order line
--   business uniqueness = (order_id, line_number)
--
-- order_date is derived deterministically from dim_date and is used for
-- BigQuery business-date partitioning.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE TABLE
`nullmarket-retail-de.nullmarket_warehouse.fact_sales`
PARTITION BY order_date
CLUSTER BY product_key, store_key
AS
SELECT
    d.full_date AS order_date,
    f.date_key,
    f.store_key,
    f.product_key,
    f.order_id,
    f.line_number,
    f.quantity,
    f.unit_price,
    f.discount_amount,
    f.unit_cost,
    f.gross_sales,
    f.net_sales,
    f.gross_margin
FROM `nullmarket-retail-de.nullmarket_warehouse._stg_fact_sales` AS f
INNER JOIN `nullmarket-retail-de.nullmarket_warehouse.dim_date` AS d
    ON f.date_key = d.date_key;

DROP TABLE
`nullmarket-retail-de.nullmarket_warehouse._stg_fact_sales`;


-- ============================================================================
-- 3. FACT_INVENTORY_SNAPSHOT
-- ============================================================================

-- ---------------------------------------------------------------------------
-- Temporary staging table
--
-- The Spark-curated inventory Parquet is Hive-style partitioned with paths
-- such as:
--   date_key=20260101/part-....parquet
--
-- date_key is therefore reconstructed from the directory path during load.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE TABLE
`nullmarket-retail-de.nullmarket_warehouse._stg_fact_inventory_snapshot`
(
    date_key          INT64,
    store_key         INT64,
    product_key       INT64,
    quantity_on_hand  INT64,
    reorder_level     INT64,
    is_low_stock      BOOL
);

LOAD DATA OVERWRITE
`nullmarket-retail-de.nullmarket_warehouse._stg_fact_inventory_snapshot`
FROM FILES (
    format = 'PARQUET',
    uris = [
        'gs://nullmarket-retail-de-data/curated/fact_inventory_snapshot/*.parquet'
    ],
    hive_partition_uri_prefix =
        'gs://nullmarket-retail-de-data/curated/fact_inventory_snapshot'
)
WITH PARTITION COLUMNS (
    date_key INT64
);

-- ---------------------------------------------------------------------------
-- Final inventory fact
--
-- Grain:
--   one row per date x store x product inventory snapshot
--   business uniqueness = (date_key, store_key, product_key)
--
-- snapshot_date is derived deterministically from dim_date and is used for
-- BigQuery business-date partitioning.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE TABLE
`nullmarket-retail-de.nullmarket_warehouse.fact_inventory_snapshot`
PARTITION BY snapshot_date
CLUSTER BY store_key, product_key
AS
SELECT
    d.full_date AS snapshot_date,
    f.date_key,
    f.store_key,
    f.product_key,
    f.quantity_on_hand,
    f.reorder_level,
    f.is_low_stock
FROM `nullmarket-retail-de.nullmarket_warehouse._stg_fact_inventory_snapshot` AS f
INNER JOIN `nullmarket-retail-de.nullmarket_warehouse.dim_date` AS d
    ON f.date_key = d.date_key;

DROP TABLE
`nullmarket-retail-de.nullmarket_warehouse._stg_fact_inventory_snapshot`;


-- ============================================================================
-- 4. FINAL TABLE INVENTORY CHECK
-- ============================================================================
-- Expected final warehouse tables:
--   dim_date
--   dim_product
--   dim_store
--   fact_inventory_snapshot
--   fact_sales
--
-- Temporary staging tables should no longer exist.
-- ============================================================================

SELECT
    table_name,
    table_type
FROM `nullmarket-retail-de.nullmarket_warehouse.INFORMATION_SCHEMA.TABLES`
WHERE table_type = 'BASE TABLE'
ORDER BY table_name;
